export const LOCAL_MODEL_HELP: readonly string[] = [
  "Local models run entirely in this browser and do not require /login.",
  "For tool use, select an 8K or larger context; the full agent prompt and tool schemas do not fit in 4K.",
  "",
  "Wllama / GGUF:",
  "  Host: hf download unsloth/Qwen3.5-2B-GGUF Qwen3.5-2B-Q4_K_M.gguf --local-dir models/qwen3.5-2b-gguf",
  "  Browser: /provider wllama",
  "           /model import qwen3.5-2b-q4km   (select the one .gguf file)",
  "           /model                          (select Qwen3.5 2B and 8K+)",
  "",
  "WebLLM / WebGPU:",
  "  Host: hf download mlc-ai/Qwen3.5-2B-q4f16_1-MLC --local-dir models/Qwen3.5-2B-q4f16_1-MLC",
  "  Browser: /provider webllm",
  "           /model import Qwen3.5-2B-q4f16_1-MLC   (select the downloaded directory)",
  "           /model                                (select Qwen3.5 2B and 8K+)",
  "  The model-library .wasm is optional; WebLLM fetches and caches it on first load.",
  "",
  "GPU setup: fully quit Chrome, run npm run chrome:webgpu, then reopen Piodide.",
  "Use /model status to inspect cached models and /model unload to release RAM/VRAM without deleting them.",
  "More detail: docs/local-models.md",
];
